# Generated by Django 6.0.1 on 2026-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ime člana tima', max_length=100, verbose_name='Ime')),
                ('last_name', models.CharField(help_text='Prezime člana tima', max_length=100, verbose_name='Prezime')),
                ('rating', models.CharField(help_text='FIDE rejting za standardni šah', max_length=4, verbose_name='Rejting')),
                ('description', models.TextField(blank=True, help_text='Biografija i postignuća člana', null=True, verbose_name='Opis')),
                ('image', models.ImageField(blank=True, help_text='Upload-ujte fotografiju člana tima', null=True, upload_to='team/', verbose_name='Fotografija')),
                ('is_active', models.BooleanField(default=True, help_text='Da li je član tima trenutno aktivan u ligi', verbose_name='Aktivan')),
                ('order', models.PositiveIntegerField(default=0, help_text='Redosled prikaza na stranici (manji broj = prvi)', verbose_name='Redosled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Član tima',
                'verbose_name_plural': 'Članovi tima',
                'ordering': ['order', 'rating', 'first_name', 'last_name'],
            },
        ),
    ]
