# Generated by Django 6.0.1 on 2026-02-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наслов')),
                ('content', models.TextField(verbose_name='Садржај')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/featured/', verbose_name='Naslovna slika')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Креирано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Датум објаве')),
                ('is_published', models.BooleanField(default=False, verbose_name='Објављено')),
            ],
            options={
                'verbose_name': 'Чланак',
                'verbose_name_plural': 'Чланци',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Име члана тима', max_length=100, verbose_name='Име')),
                ('last_name', models.CharField(help_text='Презиме члана тима', max_length=100, verbose_name='Презиме')),
                ('fide_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ФИДЕ број')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рејтинг')),
                ('description', models.TextField(blank=True, help_text='Биографија и постигнућа члана', null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, help_text='Окачи фотографију члана тима', null=True, upload_to='team/', verbose_name='Фотографија')),
                ('is_active', models.BooleanField(default=True, help_text='Да ли је члан тима тренутно активан у лиги', verbose_name='Активан')),
                ('order', models.PositiveIntegerField(default=1, help_text='Редослед приказа на страници (мањи број=1; 0 за капитена; 1 за првотимце; 2 за остале)', verbose_name='Редослед')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Креирано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ажурирано')),
            ],
            options={
                'verbose_name': 'Члан тима',
                'verbose_name_plural': 'Чланови тима',
                'ordering': ['order', 'rating', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClubTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назив турнира', max_length=100, verbose_name='Назив')),
                ('description', models.TextField(help_text='Опис турнира', verbose_name='Опис турнира')),
                ('start_date', models.DateField(verbose_name='Почетак')),
                ('end_date', models.DateField(verbose_name='Крај')),
                ('rounds', models.PositiveIntegerField(default=0, help_text='Број кола', verbose_name='Кола')),
                ('time_control_mins', models.PositiveIntegerField(default=0, help_text='Време(минути)', verbose_name='Време')),
                ('increment', models.PositiveIntegerField(default=0, help_text='Додатак по потезу(секунде)', verbose_name='Додатак')),
                ('status', models.IntegerField(choices=[(0, 'У најави'), (1, 'Отворена регистрација'), (2, 'У току'), (3, 'Завршен')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турнири',
                'ordering': ['status', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='LeagueStatisticsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назив статистичког податка', max_length=100, verbose_name='Назив статистичког податка')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Вредност статистичког податка')),
                ('is_active', models.BooleanField(default=True, help_text='Да ли се податак тренутно приказује на страници', verbose_name='Активан')),
                ('order', models.PositiveIntegerField(default=0, help_text='Редослед приказа на страници (мањи број=1)', verbose_name='Редослед')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Креирано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ажурирано')),
            ],
            options={
                'verbose_name': 'Статистички податак о лиги',
                'verbose_name_plural': 'Статистички подаци о лиги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Слика')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Опис слике')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web_page.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
