# Generated by Django 6.0.1 on 2026-02-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naziv turnira', max_length=100)),
                ('description', models.TextField(help_text='Opis turnira')),
                ('start_date', models.DateTimeField(verbose_name='Početak')),
                ('end_date', models.DateTimeField(verbose_name='Kraj')),
                ('rounds', models.PositiveIntegerField(default=0, help_text='Broj kola', verbose_name='Kola')),
                ('time_control_mins', models.PositiveIntegerField(default=0, help_text='Vreme(minuti)', verbose_name='Vreme')),
                ('increment', models.PositiveIntegerField(default=0, help_text='Dodatak po potezu(sekunde)', verbose_name='Dodatak')),
                ('status', models.CharField(choices=[('upcoming', 'U najavi'), ('registration', 'Registracija otvorena'), ('ongoing', 'U toku'), ('completed', 'Završen')], default='upcoming', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
