# Generated by Django 6.0.1 on 2026-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0002_clubtournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubtournament',
            options={'ordering': ['status', 'end_date'], 'verbose_name': 'Turnir', 'verbose_name_plural': 'Turniri'},
        ),
        migrations.AlterField(
            model_name='clubtournament',
            name='description',
            field=models.TextField(help_text='Opis turnira', verbose_name='Opis turnira'),
        ),
        migrations.AlterField(
            model_name='clubtournament',
            name='name',
            field=models.CharField(help_text='Naziv turnira', max_length=100, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='clubtournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Upcoming'), (1, 'Registration Open'), (2, 'Ongoing'), (3, 'Completed')], default=0),
        ),
    ]
