# Generated by Django 6.0.1 on 2026-02-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0003_alter_clubtournament_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='fide_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FIDE ID'),
        ),
        migrations.AlterField(
            model_name='clubtournament',
            name='end_date',
            field=models.DateField(verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='clubtournament',
            name='start_date',
            field=models.DateField(verbose_name='Početak'),
        ),
    ]
