# Generated by Django 6.0.1 on 2026-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0004_clubmember_fide_id_alter_clubtournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rejting'),
        ),
    ]
