# Generated by Django 6.0.1 on 2026-02-09 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.CharField(max_length=20, unique=True)),
                ('fen', models.TextField(help_text='Forsyth-Edwards Notation')),
                ('moves', models.TextField(help_text='Comma-separated UCI moves')),
                ('rating', models.IntegerField(default=1500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)])),
                ('rating_deviation', models.IntegerField(default=100)),
                ('popularity', models.IntegerField(default=50)),
                ('nb_plays', models.IntegerField(default=0)),
                ('themes', models.TextField(blank=True)),
                ('game_url', models.URLField(blank=True)),
                ('opening_tags', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'puzzle_id'],
            },
        ),
    ]
